/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'berinle' at '12/8/15 2:45 PM' with Gradle 2.9
 *
 * @author berinle, @date 12/8/15 2:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
      System.out.println("[java] called someLibraryMethod");
      new GroovyComponent().helloWorld();
        return true;
    }
}
